### ISSUE TITLE
Unable to bridge

### ISSUE THREAD

**Issue by KBK74** [hkey0/EclipseBridge#5]
Unable to bridge on chrome or brave, will not activate a pop up for the wallet approval.

**Comment by hkey0** [comment]
Can you share the console logs with your browser version?

**Comment by alexandroff-h** [comment]
<img width="1462" alt="image" src="https://github.com/hkey0/EclipseBridge/assets/20513666/5c8b1a8a-aa5d-4023-ad95-7ef6777b9b65">
Chrome 118

**Comment by alexandroff-h** [comment]
One more interesting thing is that if I leave the wallet field empty, it initiates the txn. It seems to be an unexpected behaviour too

**Comment by hkey0** [comment]
> <img alt="image" width="1462" src="https://private-user-images.githubusercontent.com/20513666/325401739-5c8b1a8a-aa5d-4023-ad95-7ef6777b9b65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1MzA5NjAsIm5iZiI6MTcxNDUzMDY2MCwicGF0aCI6Ii8yMDUxMzY2Ni8zMjU0MDE3MzktNWM4YjFhOGEtYWE1ZC00MDIzLWFkOTUtN2VmNjc3N2I5YjY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDAyMzEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNzFmM2UxOGQ4YmY2YmFiNmZmMmMxMmI3NzY3NWE2OTM3ZGUzY2ExMGMxMTk5NmFlOTFmNGQ5NmMwOTAxYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NjJECNSXBGFs_0UEZ6NaNN3BNZ4MENogfGn17KWzv1o"> Chrome 118

You need to enter your Solana address in the address field.


> One more interesting thing is that if I leave the wallet field empty, it initiates the txn. It seems to be an unexpected behaviour too

Yes, you are right, this is unexpected. Thanks, I'll fix it.

**Comment by alexandroff-h** [comment]
You’re welcome mate, thanks!

**Comment by lidongxin112** [comment]
Hello,I think this problem is opening,what time can you make it sure
