### ISSUE TITLE
M

### ISSUE THREAD

**Issue by Juliates** [hkey0/EclipseBridge#6]
Test network

**Comment by Juliates** [comment]
MetaMask is not connected to the Sepolia-Eclipse bridge.

**Comment by Juliates** [comment]
MetaMask is not connected to the Sepolia-Eclipse bridge.

**Comment by hkey0** [comment]
You must explain your problem in detail

**Comment by Juliates** [comment]
I recently installed the Salmon Wallet extension on Chrome and was
attempting to transfer Sepolia ETH from my MetaMask wallet to my Salmon
Wallet. However, I encountered an issue when trying to connect MetaMask to
the Sopolia-Eclipse bridge. Despite multiple attempts, clearing cookies,
and restarting my computer, I am unable to initiate the connection. Each
time I press the connect button, nothing happens.
Thanks.

**Comment by Juliates** [comment]
Just wanted to give a quick update on the bridge issue I reported earlier. Turns out, the problem was on my end- removing a conflicting browser extension fixed it. My apologies for any confusion, and a huge thanks to the team for their support! The bridge is working smoothly now.
