### ISSUE TITLE
find two bugs

### ISSUE THREAD

**Issue by crisxuan** [hkey0/EclipseBridge#8]
bug one : it seems like that my wallet cannot connect to the website
![image](https://github.com/hkey0/EclipseBridge/assets/33996561/f83cdece-5485-48ab-8b5f-072ed7ad08c3)

bug two: when i click on the bridge , i found errors in the DevTools .
![image](https://github.com/hkey0/EclipseBridge/assets/33996561/d4f14a63-c615-4dcb-8609-e066bce98d60)

**Comment by hkey0** [comment]
Hello, 
Thanks for reporting. I just fixed it. https://github.com/hkey0/EclipseBridge/commit/f522aec7b3c925a507edcb768fe248550eb4609b
And you have to connect with metamask.

Have a nice day!
